Really fixed GNU for ptime

diff --git a/bin/ptime b/bin/ptime
--- a/bin/ptime
+++ b/bin/ptime
@@ -9,10 +9,12 @@ GNU=0
 # Default is GNU, so this sets $GNU to 1 (false) if the system isn't GNU
 # On GNU: date -d @"$DATE"
 # On BSD: date -r "$DATE"
-if [[ $(date -d @1234567890 &> /dev/null) != 0 ]]; then
-  # GNU command didn't work
-  GNU=1
-fi
+
+# Try the GNU date command
+date -d @1234567890 &> /dev/null
+
+# Set $GNU equal to the return value of the previous command
+GNU=$?
 
 
 
